novotnyllc/MSBuildSdkExtras

src/build/netstandard1.0/MSBuild.Sdk.Extras.targets
This fixes a couple issues in the v1.0.1 version that was ported to this project.
See https://github.com/AArnott/NuGet4698Workaround/commit/ca908702ad36349b5e8864c6535a458fcf6e5249 and https://github.com/AArnott/NuGet4698Workaround/commit/0eb704fc43c01f8ef9d729faa94567d5acb704b5
=> Port nuget 4698 workaround v1.0.2

MSBuild.Sdk.Extras/build/platforms/NETFramework.targets
WPF is only ever supported on Windows, so don't include the Wpf.targets file.
=> Don't include WPF on non-Windows. Fixes #33

MSBuild.Sdk.Extras/build/platforms/Windows.targets
By setting TargetPlatformVersion msbuild selects the right Windows.winmd File for the win81 Target. Without it selectes the Windows.winmd
(...\Windows Kits\8.0\References\CommonConfiguration\Neutral\Windows.winmd)
file for Windows 8.0 which leads to compilation errors because of missing APIs.
=> use Windows 8.1 Api for win81 builds (...\Windows Kits\8.1\References\CommonConfiguration\Neutral\Windows.winmd)

MSBuild.Sdk.Extras/Sdk/Sdk.props, MSBuild.Sdk.Extras/Sdk/Sdk.targets, version.json
This allows referencing the extras with the simplified syntax:
```
<Project Sdk="MSBuild.Sdk.Extras/1.2.2">
...
</Project>
```
The Microsoft.NET.Sdk is automatically imported at the right
time, so the workaround for Microsoft/msbuild#1045 is no longer
needed.
=> Add SDK artifacts

MSBuild.Sdk.Extras/MSBuild.Sdk.Extras.csproj, MSBuild.Sdk.Extras/MSBuild.Sdk.Extras.targets
Locally testing nuget-producing projects is always a bit tricky.
You have to basically:
1 - Clean the output folder from previously produced packages
2 - Add the output folder as a nuget source on the consuming project
3 - Clean the nuget restore cache so that the newly produced .nupkg
from the new source will always be unpacked, rather than picked
up from a previous build already cached
4 - Repeat for every project that produces packages ;-)
We can do better!
This change adds a target `_LocalPublish` that will only run on local
builds, which does all of the above, but copying the output to
`%TEMP%\packages`, so that to test packages, you only need to add a single
source in a `NuGet.Config` (could even be a machine-wide one ;)):
```xml
<configuration>
<packageSources>
<add key="local" …
```
=> Publish locally produced nuget package for easy consumption

MSBuild.Sdk.Extras/build/platforms/MonoAndroid.targets, MSBuild.Sdk.Extras/build/platforms/languageTargets/MonoAndroid.targets, MSBuild.Sdk.Extras/build/platforms/languageTargets/Xamarin.Mac.targets, MSBuild.Sdk.Extras/build/platforms/languageTargets/Xamarin.TVOS.targets, MSBuild.Sdk.Extras/build/platforms/languageTargets/Xamarin.WatchOS.targets, MSBuild.Sdk.Extras/build/platforms/languageTargets/Xamarin.iOS.targets
The ability to build a binding library (as opposed to a normal class library) is beneficial if you are adding native resources that must be embedded into the final assembly.
Examples would be
- a native iOS .framework
- a native Android .so
- a native macOS .dylib
These _can_ be added to the package as part of a build/.targets combination, but this does not cater for other tooling that may be used, such as designers or Xamarin.Workbooks which look inside the assembly.
Current support:
- Xamarin.Mac
- Xamarin.WatchOS
- Xamarin.TVOS
- Xamarin.iOS
- Xamarin.Android
The project format is the same as usual, except for a property that indicates that this is a binding project:
```xml
<IsBindingProject>true</IsBindingProject>
```
An example file:
```xml
<Project Sdk="Microsoft.NET.Sdk"> …
```
=> Support building Xamarin binding projects

MSBuild.Sdk.Extras/MSBuild.Sdk.Extras.targets
Since this project itself is only ever built on AppVeyor, the extra
checks I brought from a general-purpose .props file don't make sense
and can actually confuse contributors, such as in #40 where support
for an extra CI system the project doesn't use in any way, broke the
IDE project loading.
=> Fix $(CI) property to only check for AppVeyor

MSBuild.Sdk.Extras/MSBuild.Sdk.Extras.targets
Ensure the copying of the new version is performed before attempting
to delete the user cache, since VS might be holding some files or
folders and delete sometimes fails, but the new package can still
work fine. Since this is sort of random, I'd rather have the build
fail *after* the local package was copied to $temp$\packages, at
which point I can try out myself to see if the deletion of the
cache is actually required or not for local testing.
=> Delete local nuget cache at the end

README.md, Source/MSBuild.Sdk.Extras/Build/Platforms.targets, Source/MSBuild.Sdk.Extras/Build/RIDs.targets, Source/MSBuild.Sdk.Extras/Sdk/Sdk.targets, Tests/ClasslibraryAsSdk/ClasslibraryAsSdk.csproj
Add support for RID's. 
What currently works: Adding a TFM with an RID like this 
```xml
<RuntimeIdentifiers Condition="'$(TargetFramework)' == 'netstandard2.0'">win;unix</RuntimeIdentifiers>
<ExtrasBuildEachRuntimeIdentifier Condition="'$(TargetFramework)' == 'netstandard2.0' or '$(TargetFramework)' == 'uap10.0.16299'">true</ExtrasBuildEachRuntimeIdentifier>
```
/cc @Drawaes @jeffkl
To Do
=> Build each RID on the inner loop

Source/MSBuild.Sdk.Extras/DefaultItems/Platforms/Xaml.targets
Files matching "Themes\*.xaml" must be added as pages and not as resources.
Otherwise it does not work with wpf applications having files like "Themes\generic.xaml" etc..
Having this not working out of the box would confuse every wpf developer i guess.
=> Fixing wrong resource include rule for wpf

Source/MSBuild.Sdk.Extras/Build/Platforms/NETFramework.targets
Fixes #127 by using MSBuildToolsVersion instead of VisualStudioVersion,
since they will no longer match after Microsoft/msbuild#3778.
I grepped for other uses of `$(VisualStudioVersion)` and at a quick glance they all look fine.
=> Find C#/VB targets using MSBuildToolsVersion

Tools/MSBuild.DevLocal.targets
Does mostly what the title says. Necessary because I'm working on some Xamarin.Mac-specific fixes (for a later PR), and these need to be tested with VSMac, on macOS. Thanks!
=> Fixes to allow restore and build on macOS

Source/MSBuild.Sdk.Extras/Build/Platforms/Windows.targets
Prior to v10.0.16299.0, the .winmd files were not placed in a versioned sub-directory.
Not only for the `UnionMetadata` but for all the other references in the `$(MSBuildProgramFiles32)\Windows Kits\10\References` folder. They were originally placed in a `Assembly.Name/Version/Assembly.Name.winmd` location.
=> Correctly select Windows.winmd on older SDKs

README.md
Just based on the recent debugging, just indicating that users should ideally use .NET Core 3.0 to compile.
=> Update the README to reflect that MSBuild.Sdk.Extras needs .NET Core 3.0

Source/MSBuild.Sdk.Extras/Build/RIDs.targets
Looks like the underlying issue was a typo with the MSBuild item metadata selector causing a combinatorial explosion in the msbuild items.
Fixes #171
=> Fix rid-tfm PDB placement issue.

Source/MSBuild.Sdk.Extras/Build/ExtrasShim.targets
Previously the changed line caused `$(ExtrasUseWindowsDesktopApp)` to be true even when the desktop Sdk is not available. `$(ExtrasUseWindowsDesktopApp)` is used to turn off Wpf and WinForms tooling provided by MSBuildSdkExtras which prevents collisions with the tooling provided by Microsoft.NET.Sdk.WindowsDesktop. That means it shouldn't be true when the sdk isn't available.
=> Fix WPF Regression #158 when .net-core 3.0 preview is not installed

Source/Directory.Build.targets, Source/MSBuild.Sdk.Extras/Build/LanguageTargets/CheckMissing.targets, TestProjects/Linux-C#/Directory.Build.props, TestProjects/Linux-C#/Linux-CS.sln, TestProjects/Linux-C#/Linux-CS/Linux-CS.sln, TestProjects/Linux-C#/Linux-CS/cross-ios-netstd2/Class1.cs, TestProjects/Linux-C#/Linux-CS/cross-ios-netstd2/cross-ios-netstd2.csproj, TestProjects/Linux-C#/Linux-CS/netstd2Library/Class1.cs, TestProjects/Linux-C#/Linux-CS/netstd2Library/netstd2Library.csproj, TestProjects/Linux-C#/cross-ios-netstd2/Class1.cs, TestProjects/Linux-C#/cross-ios-netstd2/cross-ios-netstd2.csproj, TestProjects/Linux-C#/netstd2Library/Class1.cs, TestProjects/Linux-C#/netstd2Library/netstd2Library.csproj, TestProjects/NuGet.config, azure-pipelines.yml
This PR fixes the scenario where building a head project should only build the proper dependency chain and ignore unknown targets (e.g. `xamarinios10` on linux).
The current behavior is the following:
```
/mnt/c/temp/msbe-linux/ClassLibrary1/ClassLibrary1.csproj error MSB4057: The target "_GetRestoreSettingsPerFramework" does not exist in the project. [/mnt/c/temp/msbe-linux/ClassLibrary1/ClassLibrary1.csproj]
```
This PR also adds validations on Linux and macOS.
For the Linux tests, the MSBuild version installed version in the azure devops hosted agents is not working properly (some missing methods in nuget), so the build needs to rely on a container that has the proper setup applied. 
See https://github.com/nventive/docker/blob/master/wasm-build/Dockerfile
=> Fix non-existing language targets restore

Source/MSBuild.Sdk.Extras/Build/Platforms/Xamarin/Xamarin.Android.targets
See: https://docs.microsoft.com/en-us/xamarin/android/deploy-test/building-apps/build-process#binding-project-build-properties
Basically, smaller, faster bindings - this does require 6.1 or later, so there's a condition for that.
This also bumps TargetFrameworkVersion to something a bit more sane (really I'd like to see this go to 9.0)
=> Use the `XAJavaInterop1` codegen by default

README.md
Tested on the latest Visual Studio for Mac
=> Removed warning for building on Mac

azure-pipelines.yml
This PR adds an extended validation matrix to ensure msbuild extras work with a wider range of .NET Core and macOS versions.
=> ci: Add validation for more macOS and netcore versions

MSBuild.Sdk.Extras.sln, README.md, Source/MSBuild.Sdk.Extras/Build/RIDs.targets, Tests/ClasslibPackNonRidSpecificCustomTfm/ClasslibPackNonRidSpecificCustomTfm.csproj, Tests/ClasslibPackNonRidSpecificCustomTfms/ClasslibPackNonRidSpecificCustomTfms.csproj, Tests/ClasslibPackNonRidSpecificDefaultTfm/ClasslibPackNonRidSpecificDefaultTfm.csproj, Tests/ClasslibPackNonRidSpecificDefaultTfms/ClasslibPackNonRidSpecificDefaultTfms.csproj, Tests/ClasslibPackNonRidSpecificSkipTfm/ClasslibPackNonRidSpecificSkipTfm.csproj, Tests/ClasslibPackNonRidSpecificSkipTfms/ClasslibPackNonRidSpecificSkipTfms.csproj, Tests/ClasslibPackRidSpecificCustomTfm/ClasslibPackRidSpecificCustomTfm.csproj, Tests/ClasslibPackRidSpecificCustomTfms/ClasslibPackRidSpecificCustomTfms.csproj, Tests/ClasslibPackRidSpecificDefaultTfm/ClasslibPackRidSpecificDefaultTfm.csproj, Tests/ClasslibPackRidSpecificDefaultTfms/ClasslibPackRidSpecificDefaultTfms.csproj, Tests/ClasslibPackRidSpecificSkipTfm/ClasslibPackRidSpecificSkipTfm.csproj, Tests/ClasslibPackRidSpecificSkipTfms/ClasslibPackRidSpecificSkipTfms.csproj, Tests/ClasslibPackTests.msbuildproj, Tests/Directory.Build.props, Tests/Directory.Build.targets
* `ExtrasIncludeDefaultProjectBuildOutputInPackTarget` allows overriding the target which packs the RID-specific build output (assemblies and symbols), fixes #217.
* Update to latest `Microsoft.Common.CrossTargeting.targets` upstream source code.
* `_SdkPrepareProjectFlavorMatrix` is now responsible for computing project flavors matrix: `TargetFramework` × `RuntimeIdentifier`.
* Reimplement `_ComputeTargetFrameworkItems` and `_WalkEachTargetPerFramework` on top of `_SdkPrepareProjectFlavorMatrix`
* Mimic `ProjectReference` item spec to simplify `_WalkEachTargetPerFramework` (by removing duplication)
* Use `MSBuildProjectFullPath` consistently, avoid `MSBuildProjectFile` or mixing those two.
* Drop no-op `_ExtrasPackageRuntimeFiles`.
* Pay attention to unnecessary metadata, use …
=> Major per-RuntimeIdentifier build refactoring

Source/MSBuild.Sdk.Extras/Build/RIDs.targets
=> Fully qualify metadata to avoid conflict between None and RidSpecificOutput

Source/MSBuild.Sdk.Extras/Build/Workarounds.props
The issue happens when BaseIntermediateOutputPath is overridden, thus
MSBuildProjectExtensionsPath gets assigned without generated suffix
even in *_wpftmp.*proj file.
Since _SdkOriginalProjectExtensionsPath didn't have a fallback value -
that prevented importing project extensions. This change adds the
fallback, making it effectively like "if there's a suffix - remove it,
otherwise use as is".
=> Fixed: WPF workaround for importing extensions does not always work

Source/MSBuild.Sdk.Extras/DefaultItems/ImplicitPackages.targets
The last version of Xamarin Forms depends on Microsoft.NETCore.UniversalWindowsPlatform 6.2.10.
So I think it's time to update the ExtrasUwpMetaPackageVersion for everybody.
=> Bump uwp meta package version from 6.2.9 to 6.2.10
